package com.android.countrypicker.common

import com.android.countrypicker.R
import com.countrypicker.countrypicker.model.Country
import java.util.*

object Utils {
    // Method to get the Country based on device locale
    fun getCountryByLocale(): Country {
        val localeCountryCode = Locale.getDefault().country
        return getCountryByCode(localeCountryCode.uppercase(Locale.getDefault()))
    }

    // Method to get a Country object based on the provided ISO country code
    private fun getCountryByCode(code: String): Country {
        return when (code) {
            "AD" -> Country("Andorra", "AD", "+376", R.drawable.flag_andorra, "EUR")
            "AE" -> Country("United Arab Emirates", "AE", "+971", R.drawable.flag_uae, "AED")
            "AF" -> Country("Afghanistan", "AF", "+93", R.drawable.flag_afghanistan, "AFN")
            "AG" -> Country("Antigua and Barbuda", "AG", "+1", R.drawable.flag_antigua_and_barbuda, "XCD")
            "AI" -> Country("Anguilla", "AI", "+1", R.drawable.flag_anguilla, "XCD")
            "AL" -> Country("Albania", "AL", "+355", R.drawable.flag_albania, "ALL")
            "AM" -> Country("Armenia", "AM", "+374", R.drawable.flag_armenia, "AMD")
            "AO" -> Country("Angola", "AO", "+244", R.drawable.flag_angola, "AOA")
            "AQ" -> Country("Antarctica", "AQ", "+672", R.drawable.flag_antarctica, "USD")
            "IO" -> Country("British Indian Ocean Territory", "IO", "+246", R.drawable.flag_british_indian_ocean_territory, "USD")
            "CC" -> Country("Cocos (Keeling) Islands", "CC", "+61", R.drawable.flag_cocos, "AUD")
            "CX" -> Country("Christmas Island", "CX", "+61", R.drawable.flag_christmas_island, "AUD")
            "IM" -> Country("Isle of Man", "IM", "+44", R.drawable.flag_isleof_man, "GBP")
            "NF" -> Country("Norfolk Islands", "NF", "+672", R.drawable.flag_norfolk_island, "AUD")
            "PS" -> Country("Palestine", "PS", "+970", R.drawable.flag_palestine, "ILS")
            "PN" -> Country("Pitcairn Islands", "PN", "+870", R.drawable.flag_pitcairn_islands, "NZD")
            "RE" -> Country("Réunion", "RE", "+262", R.drawable.flag_martinique, "EUR")
            "PM" -> Country("Saint Pierre and Miquelon", "PM", "+508", R.drawable.flag_saint_pierre, "EUR")
            "SX" -> Country("Sint Maarten", "SX", "+1", R.drawable.flag_sint_maarten, "ANG")
            "TK" -> Country("Tokelau", "TK", "+690", R.drawable.flag_tokelau, "NZD")
            "WF" -> Country("Wallis and Futuna", "WF", "+681", R.drawable.flag_wallis_and_futuna, "XPF")
            "YT" -> Country("Mayotte", "YT", "+262", R.drawable.flag_martinique, "EUR")
            "AR" -> Country("Argentina", "AR", "+54", R.drawable.flag_argentina, "ARS")
            "AS" -> Country("American Samoa", "AS", "+1", R.drawable.flag_american_samoa, "USD")
            "AT" -> Country("Austria", "AT", "+43", R.drawable.flag_austria, "EUR")
            "AU" -> Country("Australia", "AU", "+61", R.drawable.flag_australia, "AUD")
            "AW" -> Country("Aruba", "AW", "+297", R.drawable.flag_aruba, "AWG")
            "AX" -> Country("Åland Islands", "AX", "+358", R.drawable.flag_aland, "EUR")
            "AZ" -> Country("Azerbaijan", "AZ", "+994", R.drawable.flag_azerbaijan, "AZN")
            "BA" -> Country("Bosnia and Herzegovina", "BA", "+387", R.drawable.flag_bosnia, "BAM")
            "BB" -> Country("Barbados", "BB", "+1", R.drawable.flag_barbados, "BBD")
            "BD" -> Country("Bangladesh", "BD", "+880", R.drawable.flag_bangladesh, "BDT")
            "BE" -> Country("Belgium", "BE", "+32", R.drawable.flag_belgium, "EUR")
            "BF" -> Country("Burkina Faso", "BF", "+226", R.drawable.flag_burkina_faso, "XOF")
            "BG" -> Country("Bulgaria", "BG", "+359", R.drawable.flag_bulgaria, "BGN")
            "BH" -> Country("Bahrain", "BH", "+973", R.drawable.flag_bahrain, "BHD")
            "BI" -> Country("Burundi", "BI", "+257", R.drawable.flag_burundi, "BIF")
            "BJ" -> Country("Benin", "BJ", "+229", R.drawable.flag_benin, "XOF")
            "BL" -> Country("Saint Barthélemy", "BL", "+590", R.drawable.flag_saint_barthelemy, "EUR")
            "BM" -> Country("Bermuda", "BM", "+1", R.drawable.flag_bermuda, "BMD")
            "BN" -> Country("Brunei Darussalam", "BN", "+673", R.drawable.flag_brunei, "BND")
            "BO" -> Country("Bolivia", "BO", "+591", R.drawable.flag_bolivia, "BOB")
            "BR" -> Country("Brazil", "BR", "+55", R.drawable.flag_brazil, "BRL")
            "BS" -> Country("Bahamas", "BS", "+1", R.drawable.flag_bahamas, "BSD")
            "BT" -> Country("Bhutan", "BT", "+975", R.drawable.flag_bhutan, "BTN")
            "BW" -> Country("Botswana", "BW", "+267", R.drawable.flag_botswana, "BWP")
            "BY" -> Country("Belarus", "BY", "+375", R.drawable.flag_belarus, "BYN")
            "BZ" -> Country("Belize", "BZ", "+501", R.drawable.flag_belize, "BZD")
            "CA" -> Country("Canada", "CA", "+1", R.drawable.flag_canada, "CAD")
            "CC" -> Country("Cocos (Keeling) Islands", "CC", "+61", R.drawable.flag_cocos, "AUD")
            "CD" -> Country("Congo (DRC)", "CD", "+243", R.drawable.flag_democratic_republic_of_the_congo, "CDF")
            "CF" -> Country("Central African Republic", "CF", "+236", R.drawable.flag_central_african_republic, "XAF")
            "CG" -> Country("Congo (Republic)", "CG", "+242", R.drawable.flag_republic_of_the_congo, "XAF")
            "CH" -> Country("Switzerland", "CH", "+41", R.drawable.flag_switzerland, "CHF")
            "CI" -> Country("Côte d'Ivoire", "CI", "+225", R.drawable.flag_cote_divoire, "XOF")
            "CK" -> Country("Cook Islands", "CK", "+682", R.drawable.flag_cook_islands, "NZD")
            "CL" -> Country("Chile", "CL", "+56", R.drawable.flag_chile, "CLP")
            "CM" -> Country("Cameroon", "CM", "+237", R.drawable.flag_cameroon, "XAF")
            "CN" -> Country("China", "CN", "+86", R.drawable.flag_china, "CNY")
            "CO" -> Country("Colombia", "CO", "+57", R.drawable.flag_colombia, "COP")
            "CR" -> Country("Costa Rica", "CR", "+506", R.drawable.flag_costa_rica, "CRC")
            "CU" -> Country("Cuba", "CU", "+53", R.drawable.flag_cuba, "CUP")
            "CV" -> Country("Cape Verde", "CV", "+238", R.drawable.flag_cape_verde, "CVE")
            "CW" -> Country("Curaçao", "CW", "+599", R.drawable.flag_curacao, "ANG")
            "CY" -> Country("Cyprus", "CY", "+357", R.drawable.flag_cyprus, "EUR")
            "CZ" -> Country("Czech Republic", "CZ", "+420", R.drawable.flag_czech_republic, "CZK")
            "DE" -> Country("Germany", "DE", "+49", R.drawable.flag_germany, "EUR")
            "DJ" -> Country("Djibouti", "DJ", "+253", R.drawable.flag_djibouti, "DJF")
            "DK" -> Country("Denmark", "DK", "+45", R.drawable.flag_denmark, "DKK")
            "DM" -> Country("Dominica", "DM", "+1", R.drawable.flag_dominica, "XCD")
            "DO" -> Country("Dominican Republic", "DO", "+1", R.drawable.flag_dominican_republic, "DOP")
            "DZ" -> Country("Algeria", "DZ", "+213", R.drawable.flag_algeria, "DZD")
            "EC" -> Country("Ecuador", "EC", "+593", R.drawable.flag_ecuador, "USD")
            "EE" -> Country("Estonia", "EE", "+372", R.drawable.flag_estonia, "EUR")
            "EG" -> Country("Egypt", "EG", "+20", R.drawable.flag_egypt, "EGP")
            "ER" -> Country("Eritrea", "ER", "+291", R.drawable.flag_eritrea, "ERN")
            "ES" -> Country("Spain", "ES", "+34", R.drawable.flag_spain, "EUR")
            "ET" -> Country("Ethiopia", "ET", "+251", R.drawable.flag_ethiopia, "ETB")
            "FI" -> Country("Finland", "FI", "+358", R.drawable.flag_finland, "EUR")
            "FJ" -> Country("Fiji", "FJ", "+679", R.drawable.flag_fiji, "FJD")
            "FM" -> Country("Micronesia", "FM", "+691", R.drawable.flag_micronesia, "USD")
            "FR" -> Country("France", "FR", "+33", R.drawable.flag_france, "EUR")
            "GA" -> Country("Gabon", "GA", "+241", R.drawable.flag_gabon, "XAF")
            "GB" -> Country("United Kingdom", "GB", "+44", R.drawable.flag_united_kingdom, "GBP")
            "GD" -> Country("Grenada", "GD", "+1", R.drawable.flag_grenada, "XCD")
            "GE" -> Country("Georgia", "GE", "+995", R.drawable.flag_georgia, "GEL")
            "GH" -> Country("Ghana", "GH", "+233", R.drawable.flag_ghana, "GHS")
            "GI" -> Country("Gibraltar", "GI", "+350", R.drawable.flag_gibraltar, "GIP")
            "GL" -> Country("Greenland", "GL", "+299", R.drawable.flag_greenland, "DKK")
            "GM" -> Country("Gambia", "GM", "+220", R.drawable.flag_gambia, "GMD")
            "GN" -> Country("Guinea", "GN", "+224", R.drawable.flag_guinea, "GNF")
            "GQ" -> Country("Equatorial Guinea", "GQ", "+240", R.drawable.flag_equatorial_guinea, "XAF")
            "GR" -> Country("Greece", "GR", "+30", R.drawable.flag_greece, "EUR")
            "GT" -> Country("Guatemala", "GT", "+502", R.drawable.flag_guatemala, "GTQ")
            "GU" -> Country("Guam", "GU", "+1", R.drawable.flag_guam, "USD")
            "GW" -> Country("Guinea-Bissau", "GW", "+245", R.drawable.flag_guinea_bissau, "XOF")
            "GY" -> Country("Guyana", "GY", "+592", R.drawable.flag_guyana, "GYD")
            "HK" -> Country("Hong Kong", "HK", "+852", R.drawable.flag_hong_kong, "HKD")
            "HN" -> Country("Honduras", "HN", "+504", R.drawable.flag_honduras, "HNL")
            "HR" -> Country("Croatia", "HR", "+385", R.drawable.flag_croatia, "HRK")
            "HT" -> Country("Haiti", "HT", "+509", R.drawable.flag_haiti, "HTG")
            "HU" -> Country("Hungary", "HU", "+36", R.drawable.flag_hungary, "HUF")
            "ID" -> Country("Indonesia", "ID", "+62", R.drawable.flag_indonesia, "IDR")
            "IE" -> Country("Ireland", "IE", "+353", R.drawable.flag_ireland, "EUR")
            "IL" -> Country("Israel", "IL", "+972", R.drawable.flag_israel, "ILS")
            "IN" -> Country("India", "IN", "+91", R.drawable.flag_india, "INR")
            "IQ" -> Country("Iraq", "IQ", "+964", R.drawable.flag_iraq_new, "IQD")
            "IR" -> Country("Iran", "IR", "+98", R.drawable.flag_iran, "IRR")
            "IS" -> Country("Iceland", "IS", "+354", R.drawable.flag_iceland, "ISK")
            "IT" -> Country("Italy", "IT", "+39", R.drawable.flag_italy, "EUR")
            "JM" -> Country("Jamaica", "JM", "+1", R.drawable.flag_jamaica, "JMD")
            "JO" -> Country("Jordan", "JO", "+962", R.drawable.flag_jordan, "JOD")
            "JP" -> Country("Japan", "JP", "+81", R.drawable.flag_japan, "JPY")
            "KE" -> Country("Kenya", "KE", "+254", R.drawable.flag_kenya, "KES")
            "KG" -> Country("Kyrgyzstan", "KG", "+996", R.drawable.flag_kyrgyzstan, "KGS")
            "KH" -> Country("Cambodia", "KH", "+855", R.drawable.flag_cambodia, "KHR")
            "KI" -> Country("Kiribati", "KI", "+686", R.drawable.flag_kiribati, "AUD")
            "KM" -> Country("Comoros", "KM", "+269", R.drawable.flag_comoros, "KMF")
            "KN" -> Country("Saint Kitts and Nevis", "KN", "+1", R.drawable.flag_saint_kitts_and_nevis, "XCD")
            "KP" -> Country("North Korea", "KP", "+850", R.drawable.flag_north_korea, "KPW")
            "KR" -> Country("South Korea", "KR", "+82", R.drawable.flag_south_korea, "KRW")
            "KW" -> Country("Kuwait", "KW", "+965", R.drawable.flag_kuwait, "KWD")
            "KZ" -> Country("Kazakhstan", "KZ", "+7", R.drawable.flag_kazakhstan, "KZT")
            "LA" -> Country("Laos", "LA", "+856", R.drawable.flag_laos, "LAK")
            "LB" -> Country("Lebanon", "LB", "+961", R.drawable.flag_lebanon, "LBP")
            "LC" -> Country("Saint Lucia", "LC", "+1", R.drawable.flag_saint_lucia, "XCD")
            "LI" -> Country("Liechtenstein", "LI", "+423", R.drawable.flag_liechtenstein, "CHF")
            "LK" -> Country("Sri Lanka", "LK", "+94", R.drawable.flag_sri_lanka, "LKR")
            "LR" -> Country("Liberia", "LR", "+231", R.drawable.flag_liberia, "LRD")
            "LS" -> Country("Lesotho", "LS", "+266", R.drawable.flag_lesotho, "LSL")
            "LT" -> Country("Lithuania", "LT", "+370", R.drawable.flag_lithuania, "EUR")
            "LU" -> Country("Luxembourg", "LU", "+352", R.drawable.flag_luxembourg, "EUR")
            "LV" -> Country("Latvia", "LV", "+371", R.drawable.flag_latvia, "EUR")
            "LY" -> Country("Libya", "LY", "+218", R.drawable.flag_libya, "LYD")
            "MA" -> Country("Morocco", "MA", "+212", R.drawable.flag_morocco, "MAD")
            "MC" -> Country("Monaco", "MC", "+377", R.drawable.flag_monaco, "EUR")
            "MD" -> Country("Moldova", "MD", "+373", R.drawable.flag_moldova, "MDL")
            "ME" -> Country("Montenegro", "ME", "+382", R.drawable.flag_of_montenegro, "EUR")
            "MF" -> Country("Saint Martin", "MF", "+590", R.drawable.flag_saint_martin, "EUR")
            "MG" -> Country("Madagascar", "MG", "+261", R.drawable.flag_madagascar, "MGA")
            "MH" -> Country("Marshall Islands", "MH", "+692", R.drawable.flag_marshall_islands, "USD")
            "MK" -> Country("Macedonia", "MK", "+389", R.drawable.flag_macedonia, "MKD")
            "ML" -> Country("Mali", "ML", "+223", R.drawable.flag_mali, "XOF")
            "MM" -> Country("Myanmar", "MM", "+95", R.drawable.flag_myanmar, "MMK")
            "MN" -> Country("Mongolia", "MN", "+976", R.drawable.flag_mongolia, "MNT")
            "MO" -> Country("Macau", "MO", "+853", R.drawable.flag_macao, "MOP")
            "MP" -> Country("Northern Mariana Islands", "MP", "+1", R.drawable.flag_northern_mariana_islands, "USD")
            "MQ" -> Country("Martinique", "MQ", "+596", R.drawable.flag_martinique, "EUR")
            "MR" -> Country("Mauritania", "MR", "+222", R.drawable.flag_mauritania, "MRU")
            "MS" -> Country("Montserrat", "MS", "+1", R.drawable.flag_montserrat, "XCD")
            "MT" -> Country("Malta", "MT", "+356", R.drawable.flag_malta, "EUR")
            "MU" -> Country("Mauritius", "MU", "+230", R.drawable.flag_mauritius, "MUR")
            "MV" -> Country("Maldives", "MV", "+960", R.drawable.flag_maldives, "MVR")
            "MW" -> Country("Malawi", "MW", "+265", R.drawable.flag_malawi, "MWK")
            "MX" -> Country("Mexico", "MX", "+52", R.drawable.flag_mexico, "MXN")
            "MY" -> Country("Malaysia", "MY", "+60", R.drawable.flag_malaysia, "MYR")
            "MZ" -> Country("Mozambique", "MZ", "+258", R.drawable.flag_mozambique, "MZN")
            "NA" -> Country("Namibia", "NA", "+264", R.drawable.flag_namibia, "NAD")
            "NC" -> Country("New Caledonia", "NC", "+687", R.drawable.flag_new_caledonia, "XPF")
            "NE" -> Country("Niger", "NE", "+227", R.drawable.flag_niger, "XOF")
            "NF" -> Country("Norfolk Island", "NF", "+672", R.drawable.flag_norfolk_island, "AUD")
            "NG" -> Country("Nigeria", "NG", "+234", R.drawable.flag_nigeria, "NGN")
            "NI" -> Country("Nicaragua", "NI", "+505", R.drawable.flag_nicaragua, "NIO")
            "NL" -> Country("Netherlands", "NL", "+31", R.drawable.flag_netherlands, "EUR")
            "NO" -> Country("Norway", "NO", "+47", R.drawable.flag_norway, "NOK")
            "NP" -> Country("Nepal", "NP", "+977", R.drawable.flag_nepal, "NPR")
            "NR" -> Country("Nauru", "NR", "+674", R.drawable.flag_nauru, "AUD")
            "NU" -> Country("Niue", "NU", "+683", R.drawable.flag_niue, "NZD")
            "NZ" -> Country("New Zealand", "NZ", "+64", R.drawable.flag_new_zealand, "NZD")
            "OM" -> Country("Oman", "OM", "+968", R.drawable.flag_oman, "OMR")
            "PA" -> Country("Panama", "PA", "+507", R.drawable.flag_panama, "PAB")
            "PE" -> Country("Peru", "PE", "+51", R.drawable.flag_peru, "PEN")
            "PF" -> Country("French Polynesia", "PF", "+689", R.drawable.flag_french_polynesia, "XPF")
            "PG" -> Country("Papua New Guinea", "PG", "+675", R.drawable.flag_papua_new_guinea, "PGK")
            "PH" -> Country("Philippines", "PH", "+63", R.drawable.flag_philippines, "PHP")
            "PK" -> Country("Pakistan", "PK", "+92", R.drawable.flag_pakistan, "PKR")
            "PL" -> Country("Poland", "PL", "+48", R.drawable.flag_poland, "PLN")
            "PM" -> Country("Saint Pierre and Miquelon", "PM", "+508", R.drawable.flag_saint_pierre, "EUR")
            "PN" -> Country("Pitcairn", "PN", "+64", R.drawable.flag_pitcairn_islands, "NZD")
            "PR" -> Country("Puerto Rico", "PR", "+1", R.drawable.flag_puerto_rico, "USD")
            "PT" -> Country("Portugal", "PT", "+351", R.drawable.flag_portugal, "EUR")
            "PW" -> Country("Palau", "PW", "+680", R.drawable.flag_palau, "USD")
            "PY" -> Country("Paraguay", "PY", "+595", R.drawable.flag_paraguay, "PYG")
            "QA" -> Country("Qatar", "QA", "+974", R.drawable.flag_qatar, "QAR")
            "RO" -> Country("Romania", "RO", "+40", R.drawable.flag_romania, "RON")
            "RS" -> Country("Serbia", "RS", "+381", R.drawable.flag_serbia, "RSD")
            "RU" -> Country("Russia", "RU", "+7", R.drawable.flag_russian_federation, "RUB")
            "RW" -> Country("Rwanda", "RW", "+250", R.drawable.flag_rwanda, "RWF")
            "SA" -> Country("Saudi Arabia", "SA", "+966", R.drawable.flag_saudi_arabia, "SAR")
            "SB" -> Country("Solomon Islands", "SB", "+677", R.drawable.flag_soloman_islands, "SBD")
            "SC" -> Country("Seychelles", "SC", "+248", R.drawable.flag_seychelles, "SCR")
            "SD" -> Country("Sudan", "SD", "+249", R.drawable.flag_sudan, "SDG")
            "SE" -> Country("Sweden", "SE", "+46", R.drawable.flag_sweden, "SEK")
            "SG" -> Country("Singapore", "SG", "+65", R.drawable.flag_singapore, "SGD")
            "SH" -> Country("Saint Helena", "SH", "+290", R.drawable.flag_saint_helena, "SHP")
            "SI" -> Country("Slovenia", "SI", "+386", R.drawable.flag_slovenia, "EUR")
            "SK" -> Country("Slovakia", "SK", "+421", R.drawable.flag_slovakia, "EUR")
            "SL" -> Country("Sierra Leone", "SL", "+232", R.drawable.flag_sierra_leone, "SLL")
            "SM" -> Country("San Marino", "SM", "+378", R.drawable.flag_san_marino, "EUR")
            "SN" -> Country("Senegal", "SN", "+221", R.drawable.flag_senegal, "XOF")
            "SO" -> Country("Somalia", "SO", "+252", R.drawable.flag_somalia, "SOS")
            "SR" -> Country("Suriname", "SR", "+597", R.drawable.flag_suriname, "SRD")
            "SS" -> Country("South Sudan", "SS", "+211", R.drawable.flag_south_sudan, "SSP")
            "ST" -> Country("Sao Tome and Principe", "ST", "+239", R.drawable.flag_sao_tome_and_principe, "STN")
            "SV" -> Country("El Salvador", "SV", "+503", R.drawable.flag_el_salvador, "USD")
            "SY" -> Country("Syria", "SY", "+963", R.drawable.flag_syria, "SYP")
            "SZ" -> Country("Eswatini", "SZ", "+268", R.drawable.flag_swaziland, "SZL")
            "TC" -> Country("Turks and Caicos Islands", "TC", "+1", R.drawable.flag_turks_and_caicos_islands, "USD")
            "TD" -> Country("Chad", "TD", "+235", R.drawable.flag_chad, "XAF")
            "TG" -> Country("Togo", "TG", "+228", R.drawable.flag_togo, "XOF")
            "TH" -> Country("Thailand", "TH", "+66", R.drawable.flag_thailand, "THB")
            "TJ" -> Country("Tajikistan", "TJ", "+992", R.drawable.flag_tajikistan, "TJS")
            "TK" -> Country("Tokelau", "TK", "+690", R.drawable.flag_tokelau, "NZD")
            "TL" -> Country("Timor-Leste", "TL", "+670", R.drawable.flag_timor_leste, "USD")
            "TM" -> Country("Turkmenistan", "TM", "+993", R.drawable.flag_turkmenistan, "TMT")
            "TN" -> Country("Tunisia", "TN", "+216", R.drawable.flag_tunisia, "TND")
            "TO" -> Country("Tonga", "TO", "+676", R.drawable.flag_tonga, "TOP")
            "TR" -> Country("Turkey", "TR", "+90", R.drawable.flag_turkey, "TRY")
            "TT" -> Country("Trinidad & Tobago", "TT", "+1", R.drawable.flag_trinidad_and_tobago, "TTD")
            "TV" -> Country("Tuvalu", "TV", "+688", R.drawable.flag_tuvalu, "AUD")
            "TW" -> Country("Taiwan", "TW", "+886", R.drawable.flag_taiwan, "TWD")
            "TZ" -> Country("Tanzania", "TZ", "+255", R.drawable.flag_tanzania, "TZS")
            "UA" -> Country("Ukraine", "UA", "+380", R.drawable.flag_ukraine, "UAH")
            "UG" -> Country("Uganda", "UG", "+256", R.drawable.flag_uganda, "UGX")
            "US" -> Country("United States", "US", "+1", R.drawable.flag_united_states_of_america, "USD")
            "UY" -> Country("Uruguay", "UY", "+598", R.drawable.flag_uruguay, "UYU")
            "UZ" -> Country("Uzbekistan", "UZ", "+998", R.drawable.flag_uzbekistan, "UZS")
            "VA" -> Country("Holy See (Vatican City)", "VA", "+379", R.drawable.flag_vatican_city, "EUR")
            "VC" -> Country("Saint Vincent and the Grenadines", "VC", "+1", R.drawable.flag_saint_vicent_and_the_grenadines, "XCD")
            "VE" -> Country("Venezuela", "VE", "+58", R.drawable.flag_venezuela, "VES")
            "VG" -> Country("British Virgin Islands", "VG", "+1", R.drawable.flag_british_virgin_islands, "USD")
            "VI" -> Country("US Virgin Islands", "VI", "+1", R.drawable.flag_us_virgin_islands, "USD")
            "VN" -> Country("Vietnam", "VN", "+84", R.drawable.flag_vietnam, "VND")
            "VU" -> Country("Vanuatu", "VU", "+678", R.drawable.flag_vanuatu, "VUV")
            "WF" -> Country("Wallis and Futuna", "WF", "+681", R.drawable.flag_wallis_and_futuna, "XPF")
            "WS" -> Country("Samoa", "WS", "+685", R.drawable.flag_samoa, "WST")
            "XK" -> Country("Kosovo", "XK", "+383", R.drawable.flag_kosovo, "EUR")
            "YE" -> Country("Yemen", "YE", "+967", R.drawable.flag_yemen, "YER")
            "ZA" -> Country("South Africa", "ZA", "+27", R.drawable.flag_south_africa, "ZAR")
            "ZM" -> Country("Zambia", "ZM", "+260", R.drawable.flag_zambia, "ZMW")
            "ZW" -> Country("Zimbabwe", "ZW", "+263", R.drawable.flag_zimbabwe, "ZWL")

            else -> Country("United States", "US", "+1", R.drawable.flag_united_states_of_america, "USD")
        }
    }
}
