package com.android.countrypicker.common

import com.android.countrypicker.R
import com.countrypicker.countrypicker.model.Country
import java.util.*

object Utils {
    // Method to get the Country based on device locale
    fun getCountryByLocale(): Country {
        val localeCountryCode = Locale.getDefault().country
        return getCountryByCode(localeCountryCode.uppercase(Locale.getDefault()))
    }

    // Method to get a Country object based on the provided ISO country code
    private fun getCountryByCode(code: String): Country {
        return when (code) {
            "AD" -> Country("Andorra", "AD", "+376", R.drawable.flag_andorra)
            "AE" -> Country("United Arab Emirates (UAE)", "AE", "+971", R.drawable.flag_uae)
            "AF" -> Country("Afghanistan", "AF", "+93", R.drawable.flag_afghanistan)
            "AG" -> Country("Antigua and Barbuda", "AG", "+1", R.drawable.flag_antigua_and_barbuda)
            "AI" -> Country("Anguilla", "AI", "+1", R.drawable.flag_anguilla)
            "AL" -> Country("Albania", "AL", "+355", R.drawable.flag_albania)
            "AM" -> Country("Armenia", "AM", "+374", R.drawable.flag_armenia)
            "AO" -> Country("Angola", "AO", "+244", R.drawable.flag_angola)
            "AQ" -> Country("Antarctica", "AQ", "+672", R.drawable.flag_antarctica)
            "AR" -> Country("Argentina", "AR", "+54", R.drawable.flag_argentina)
            "AS" -> Country("American Samoa", "AS", "+1", R.drawable.flag_american_samoa)
            "AT" -> Country("Austria", "AT", "+43", R.drawable.flag_austria)
            "AU" -> Country("Australia", "AU", "+61", R.drawable.flag_australia)
            "AW" -> Country("Aruba", "AW", "+297", R.drawable.flag_aruba)
            "AX" -> Country("Åland Islands", "AX", "+358", R.drawable.flag_aland)
            "AZ" -> Country("Azerbaijan", "AZ", "+994", R.drawable.flag_azerbaijan)
            "BA" -> Country("Bosnia And Herzegovina", "BA", "+387", R.drawable.flag_bosnia)
            "BB" -> Country("Barbados", "BB", "+1", R.drawable.flag_barbados)
            "BD" -> Country("Bangladesh", "BD", "+880", R.drawable.flag_bangladesh)
            "BE" -> Country("Belgium", "BE", "+32", R.drawable.flag_belgium)
            "BF" -> Country("Burkina Faso", "BF", "+226", R.drawable.flag_burkina_faso)
            "BG" -> Country("Bulgaria", "BG", "+359", R.drawable.flag_bulgaria)
            "BH" -> Country("Bahrain", "BH", "+973", R.drawable.flag_bahrain)
            "BI" -> Country("Burundi", "BI", "+257", R.drawable.flag_burundi)
            "BJ" -> Country("Benin", "BJ", "+229", R.drawable.flag_benin)
            "BL" -> Country("Saint Barthélemy", "BL", "+590", R.drawable.flag_saint_barthelemy)
            "BM" -> Country("Bermuda", "BM", "+1", R.drawable.flag_bermuda)
            "BN" -> Country("Brunei Darussalam", "BN", "+673", R.drawable.flag_brunei)
            "BO" -> Country("Bolivia, Plurinational State Of", "BO", "+591", R.drawable.flag_bolivia)
            "BR" -> Country("Brazil", "BR", "+55", R.drawable.flag_brazil)
            "BS" -> Country("Bahamas", "BS", "+1", R.drawable.flag_bahamas)
            "BT" -> Country("Bhutan", "BT", "+975", R.drawable.flag_bhutan)
            "BW" -> Country("Botswana", "BW", "+267", R.drawable.flag_botswana)
            "BY" -> Country("Belarus", "BY", "+375", R.drawable.flag_belarus)
            "BZ" -> Country("Belize", "BZ", "+501", R.drawable.flag_belize)
            "CA" -> Country("Canada", "CA", "+1", R.drawable.flag_canada)
            "CC" -> Country("Cocos (Keeling) Islands", "CC", "+61", R.drawable.flag_cocos)
            "CD" -> Country("Congo, The Democratic Republic Of The", "CD", "+243", R.drawable.flag_democratic_republic_of_the_congo)
            "CF" -> Country("Central African Republic", "CF", "+236", R.drawable.flag_central_african_republic)
            "CG" -> Country("Congo", "CG", "+242", R.drawable.flag_republic_of_the_congo)
            "CH" -> Country("Switzerland", "CH", "+41", R.drawable.flag_switzerland)
            "CI" -> Country("Côte D'ivoire", "CI", "+225", R.drawable.flag_cote_divoire)
            "CK" -> Country("Cook Islands", "CK", "+682", R.drawable.flag_cook_islands)
            "CL" -> Country("Chile", "CL", "+56", R.drawable.flag_chile)
            "CM" -> Country("Cameroon", "CM", "+237", R.drawable.flag_cameroon)
            "CN" -> Country("China", "CN", "+86", R.drawable.flag_china)
            "CO" -> Country("Colombia", "CO", "+57", R.drawable.flag_colombia)
            "CR" -> Country("Costa Rica", "CR", "+506", R.drawable.flag_costa_rica)
            "CU" -> Country("Cuba", "CU", "+53", R.drawable.flag_cuba)
            "CV" -> Country("Cape Verde", "CV", "+238", R.drawable.flag_cape_verde)
            "CW" -> Country("Curaçao", "CW", "+599", R.drawable.flag_curacao)
            "CX" -> Country("Christmas Island", "CX", "+61", R.drawable.flag_christmas_island)
            "CY" -> Country("Cyprus", "CY", "+357", R.drawable.flag_cyprus)
            "CZ" -> Country("Czech Republic", "CZ", "+420", R.drawable.flag_czech_republic)
            "DE" -> Country("Germany", "DE", "+49", R.drawable.flag_germany)
            "DJ" -> Country("Djibouti", "DJ", "+253", R.drawable.flag_djibouti)
            "DK" -> Country("Denmark", "DK", "+45", R.drawable.flag_denmark)
            "DM" -> Country("Dominica", "DM", "+1", R.drawable.flag_dominica)
            "DO" -> Country("Dominican Republic", "DO", "+1", R.drawable.flag_dominican_republic)
            "DZ" -> Country("Algeria", "DZ", "+213", R.drawable.flag_algeria)
            "EC" -> Country("Ecuador", "EC", "+593", R.drawable.flag_ecuador)
            "EE" -> Country("Estonia", "EE", "+372", R.drawable.flag_estonia)
            "EG" -> Country("Egypt", "EG", "+20", R.drawable.flag_egypt)
            "ER" -> Country("Eritrea", "ER", "+291", R.drawable.flag_eritrea)
            "ES" -> Country("Spain", "ES", "+34", R.drawable.flag_spain)
            "ET" -> Country("Ethiopia", "ET", "+251", R.drawable.flag_ethiopia)
            "FI" -> Country("Finland", "FI", "+358", R.drawable.flag_finland)
            "FJ" -> Country("Fiji", "FJ", "+679", R.drawable.flag_fiji)
            "FK" -> Country("Falkland Islands (Malvinas)", "FK", "+500", R.drawable.flag_falkland_islands)
            "FM" -> Country("Micronesia, Federated States Of", "FM", "+691", R.drawable.flag_micronesia)
            "FO" -> Country("Faroe Islands", "FO", "+298", R.drawable.flag_faroe_islands)
            "FR" -> Country("France", "FR", "+33", R.drawable.flag_france)
            "GA" -> Country("Gabon", "GA", "+241", R.drawable.flag_gabon)
            "GB" -> Country("United Kingdom", "GB", "+44", R.drawable.flag_united_kingdom)
            "GD" -> Country("Grenada", "GD", "+1", R.drawable.flag_grenada)
            "GE" -> Country("Georgia", "GE", "+995", R.drawable.flag_georgia)
            "GF" -> Country("French Guyana", "GF", "+594", R.drawable.flag_guyane)
            "GH" -> Country("Ghana", "GH", "+233", R.drawable.flag_ghana)
            "GI" -> Country("Gibraltar", "GI", "+350", R.drawable.flag_gibraltar)
            "GL" -> Country("Greenland", "GL", "+299", R.drawable.flag_greenland)
            "GM" -> Country("Gambia", "GM", "+220", R.drawable.flag_gambia)
            "GN" -> Country("Guinea", "GN", "+224", R.drawable.flag_guinea)
            "GP" -> Country("Guadeloupe", "GP", "+450", R.drawable.flag_guadeloupe)
            "GQ" -> Country("Equatorial Guinea", "GQ", "+240", R.drawable.flag_equatorial_guinea)
            "GR" -> Country("Greece", "GR", "+30", R.drawable.flag_greece)
            "GT" -> Country("Guatemala", "GT", "+502", R.drawable.flag_guatemala)
            "GU" -> Country("Guam", "GU", "+1", R.drawable.flag_guam)
            "GW" -> Country("Guinea-bissau", "GW", "+245", R.drawable.flag_guinea_bissau)
            "GY" -> Country("Guyana", "GY", "+592", R.drawable.flag_guyana)
            "HK" -> Country("Hong Kong", "HK", "+852", R.drawable.flag_hong_kong)
            "HN" -> Country("Honduras", "HN", "+504", R.drawable.flag_honduras)
            "HR" -> Country("Croatia", "HR", "+385", R.drawable.flag_croatia)
            "HT" -> Country("Haiti", "HT", "+509", R.drawable.flag_haiti)
            "HU" -> Country("Hungary", "HU", "+36", R.drawable.flag_hungary)
            "ID" -> Country("Indonesia", "ID", "+62", R.drawable.flag_indonesia)
            "IE" -> Country("Ireland", "IE", "+353", R.drawable.flag_ireland)
            "IL" -> Country("Israel", "IL", "+972", R.drawable.flag_israel)
            "IM" -> Country("Isle Of Man", "IM", "+44", R.drawable.flag_isleof_man)
            "IN" -> Country("India", "IN", "+91", R.drawable.flag_india)
            "IO" -> Country("British Indian Ocean Territory", "IO", "+246", R.drawable.flag_british_indian_ocean_territory)
            "IQ" -> Country("Iraq", "IQ", "+964", R.drawable.flag_iraq_new)
            "IR" -> Country("Iran, Islamic Republic Of", "IR", "+98", R.drawable.flag_iran)
            "IS" -> Country("Iceland", "IS", "+354", R.drawable.flag_iceland)
            "IT" -> Country("Italy", "IT", "+39", R.drawable.flag_italy)
            "JM" -> Country("Jamaica", "JM", "+1", R.drawable.flag_jamaica)
            "JO" -> Country("Jordan", "JO", "+962", R.drawable.flag_jordan)
            "JP" -> Country("Japan", "JP", "+81", R.drawable.flag_japan)
            "KE" -> Country("Kenya", "KE", "+254", R.drawable.flag_kenya)
            "KG" -> Country("Kyrgyzstan", "KG", "+996", R.drawable.flag_kyrgyzstan)
            "KH" -> Country("Cambodia", "KH", "+855", R.drawable.flag_cambodia)
            "KI" -> Country("Kiribati", "KI", "+686", R.drawable.flag_kiribati)
            "KM" -> Country("Comoros", "KM", "+269", R.drawable.flag_comoros)
            "KN" -> Country("Saint Kitts and Nevis", "KN", "+1", R.drawable.flag_saint_kitts_and_nevis)
            "KP" -> Country("North Korea", "KP", "+850", R.drawable.flag_north_korea)
            "KR" -> Country("South Korea", "KR", "+82", R.drawable.flag_south_korea)
            "KW" -> Country("Kuwait", "KW", "+965", R.drawable.flag_kuwait)
            "KY" -> Country("Cayman Islands", "KY", "+1", R.drawable.flag_cayman_islands)
            "KZ" -> Country("Kazakhstan", "KZ", "+7", R.drawable.flag_kazakhstan)
            "LA" -> Country("Lao People's Democratic Republic", "LA", "+856", R.drawable.flag_laos)
            "LB" -> Country("Lebanon", "LB", "+961", R.drawable.flag_lebanon)
            "LC" -> Country("Saint Lucia", "LC", "+1", R.drawable.flag_saint_lucia)
            "LI" -> Country("Liechtenstein", "LI", "+423", R.drawable.flag_liechtenstein)
            "LK" -> Country("Sri Lanka", "LK", "+94", R.drawable.flag_sri_lanka)
            "LR" -> Country("Liberia", "LR", "+231", R.drawable.flag_liberia)
            "LS" -> Country("Lesotho", "LS", "+266", R.drawable.flag_lesotho)
            "LT" -> Country("Lithuania", "LT", "+370", R.drawable.flag_lithuania)
            "LU" -> Country("Luxembourg", "LU", "+352", R.drawable.flag_luxembourg)
            "LV" -> Country("Latvia", "LV", "+371", R.drawable.flag_latvia)
            "LY" -> Country("Libya", "LY", "+218", R.drawable.flag_libya)
            "MA" -> Country("Morocco", "MA", "+212", R.drawable.flag_morocco)
            "MC" -> Country("Monaco", "MC", "+377", R.drawable.flag_monaco)
            "MD" -> Country("Moldova, Republic Of", "MD", "+373", R.drawable.flag_moldova)
            "ME" -> Country("Montenegro", "ME", "+382", R.drawable.flag_of_montenegro)
            "MF" -> Country("Saint Martin", "MF", "+590", R.drawable.flag_saint_martin)
            "MG" -> Country("Madagascar", "MG", "+261", R.drawable.flag_madagascar)
            "MH" -> Country("Marshall Islands", "MH", "+692", R.drawable.flag_marshall_islands)
            "MK" -> Country("Macedonia (FYROM)", "MK", "+389", R.drawable.flag_macedonia)
            "ML" -> Country("Mali", "ML", "+223", R.drawable.flag_mali)
            "MM" -> Country("Myanmar", "MM", "+95", R.drawable.flag_myanmar)
            "MN" -> Country("Mongolia", "MN", "+976", R.drawable.flag_mongolia)
            "MO" -> Country("Macau", "MO", "+853", R.drawable.flag_macao)
            "MP" -> Country("Northern Mariana Islands", "MP", "+1", R.drawable.flag_northern_mariana_islands)
            "MQ" -> Country("Martinique", "MQ", "+596", R.drawable.flag_martinique)
            "MR" -> Country("Mauritania", "MR", "+222", R.drawable.flag_mauritania)
            "MS" -> Country("Montserrat", "MS", "+1", R.drawable.flag_montserrat)
            "MT" -> Country("Malta", "MT", "+356", R.drawable.flag_malta)
            "MU" -> Country("Mauritius", "MU", "+230", R.drawable.flag_mauritius)
            "MV" -> Country("Maldives", "MV", "+960", R.drawable.flag_maldives)
            "MW" -> Country("Malawi", "MW", "+265", R.drawable.flag_malawi)
            "MX" -> Country("Mexico", "MX", "+52", R.drawable.flag_mexico)
            "MY" -> Country("Malaysia", "MY", "+60", R.drawable.flag_malaysia)
            "MZ" -> Country("Mozambique", "MZ", "+258", R.drawable.flag_mozambique)
            "NA" -> Country("Namibia", "NA", "+264", R.drawable.flag_namibia)
            "NC" -> Country("New Caledonia", "NC", "+687", R.drawable.flag_new_caledonia)
            "NE" -> Country("Niger", "NE", "+227", R.drawable.flag_niger)
            "NF" -> Country("Norfolk Islands", "NF", "+672", R.drawable.flag_norfolk_island)
            "NG" -> Country("Nigeria", "NG", "+234", R.drawable.flag_nigeria)
            "NI" -> Country("Nicaragua", "NI", "+505", R.drawable.flag_nicaragua)
            "NL" -> Country("Netherlands", "NL", "+31", R.drawable.flag_netherlands)
            "NO" -> Country("Norway", "NO", "+47", R.drawable.flag_norway)
            "NP" -> Country("Nepal", "NP", "+977", R.drawable.flag_nepal)
            "NR" -> Country("Nauru", "NR", "+674", R.drawable.flag_nauru)
            "NU" -> Country("Niue", "NU", "+683", R.drawable.flag_niue)
            "NZ" -> Country("New Zealand", "NZ", "+64", R.drawable.flag_new_zealand)
            "OM" -> Country("Oman", "OM", "+968", R.drawable.flag_oman)
            "PA" -> Country("Panama", "PA", "+507", R.drawable.flag_panama)
            "PE" -> Country("Peru", "PE", "+51", R.drawable.flag_peru)
            "PF" -> Country("French Polynesia", "PF", "+689", R.drawable.flag_french_polynesia)
            "PG" -> Country("Papua New Guinea", "PG", "+675", R.drawable.flag_papua_new_guinea)
            "PH" -> Country("Philippines", "PH", "+63", R.drawable.flag_philippines)
            "PK" -> Country("Pakistan", "PK", "+92", R.drawable.flag_pakistan)
            "PL" -> Country("Poland", "PL", "+48", R.drawable.flag_poland)
            "PM" -> Country("Saint Pierre And Miquelon", "PM", "+508", R.drawable.flag_saint_pierre)
            "PN" -> Country("Pitcairn Islands", "PN", "+870", R.drawable.flag_pitcairn_islands)
            "PR" -> Country("Puerto Rico", "PR", "+1", R.drawable.flag_puerto_rico)
            "PS" -> Country("Palestine", "PS", "+970", R.drawable.flag_palestine)
            "PT" -> Country("Portugal", "PT", "+351", R.drawable.flag_portugal)
            "PW" -> Country("Palau", "PW", "+680", R.drawable.flag_palau)
            "PY" -> Country("Paraguay", "PY", "+595", R.drawable.flag_paraguay)
            "QA" -> Country("Qatar", "QA", "+974", R.drawable.flag_qatar)
            "RE" -> Country("Réunion", "RE", "+262", R.drawable.flag_martinique)
            "RO" -> Country("Romania", "RO", "+40", R.drawable.flag_romania)
            "RS" -> Country("Serbia", "RS", "+381", R.drawable.flag_serbia)
            "RU" -> Country("Russian Federation", "RU", "+7", R.drawable.flag_russian_federation)
            "RW" -> Country("Rwanda", "RW", "+250", R.drawable.flag_rwanda)
            "SA" -> Country("Saudi Arabia", "SA", "+966", R.drawable.flag_saudi_arabia)
            "SB" -> Country("Solomon Islands", "SB", "+677", R.drawable.flag_soloman_islands)
            "SC" -> Country("Seychelles", "SC", "+248", R.drawable.flag_seychelles)
            "SD" -> Country("Sudan", "SD", "+249", R.drawable.flag_sudan)
            "SE" -> Country("Sweden", "SE", "+46", R.drawable.flag_sweden)
            "SG" -> Country("Singapore", "SG", "+65", R.drawable.flag_singapore)
            "SH" -> Country("Saint Helena, Ascension And Tristan Da Cunha", "SH", "+290", R.drawable.flag_saint_helena)
            "SI" -> Country("Slovenia", "SI", "+386", R.drawable.flag_slovenia)
            "SK" -> Country("Slovakia", "SK", "+421", R.drawable.flag_slovakia)
            "SL" -> Country("Sierra Leone", "SL", "+232", R.drawable.flag_sierra_leone)
            "SM" -> Country("San Marino", "SM", "+378", R.drawable.flag_san_marino)
            "SN" -> Country("Senegal", "SN", "+221", R.drawable.flag_senegal)
            "SO" -> Country("Somalia", "SO", "+252", R.drawable.flag_somalia)
            "SR" -> Country("Suriname", "SR", "+597", R.drawable.flag_suriname)
            "SS" -> Country("South Sudan", "SS", "+211", R.drawable.flag_south_sudan)
            "ST" -> Country("Sao Tome And Principe", "ST", "+239", R.drawable.flag_sao_tome_and_principe)
            "SV" -> Country("El Salvador", "SV", "+503", R.drawable.flag_el_salvador)
            "SX" -> Country("Sint Maarten", "SX", "+1", R.drawable.flag_sint_maarten)
            "SY" -> Country("Syrian Arab Republic", "SY", "+963", R.drawable.flag_syria)
            "SZ" -> Country("Swaziland", "SZ", "+268", R.drawable.flag_swaziland)
            "TC" -> Country("Turks and Caicos Islands", "TC", "+1", R.drawable.flag_turks_and_caicos_islands)
            "TD" -> Country("Chad", "TD", "+235", R.drawable.flag_chad)
            "TG" -> Country("Togo", "TG", "+228", R.drawable.flag_togo)
            "TH" -> Country("Thailand", "TH", "+66", R.drawable.flag_thailand)
            "TJ" -> Country("Tajikistan", "TJ", "+992", R.drawable.flag_tajikistan)
            "TK" -> Country("Tokelau", "TK", "+690", R.drawable.flag_tokelau)
            "TL" -> Country("Timor-leste", "TL", "+670", R.drawable.flag_timor_leste)
            "TM" -> Country("Turkmenistan", "TM", "+993", R.drawable.flag_turkmenistan)
            "TN" -> Country("Tunisia", "TN", "+216", R.drawable.flag_tunisia)
            "TO" -> Country("Tonga", "TO", "+676", R.drawable.flag_tonga)
            "TR" -> Country("Turkey", "TR", "+90", R.drawable.flag_turkey)
            "TT" -> Country("Trinidad & Tobago", "TT", "+1", R.drawable.flag_trinidad_and_tobago)
            "TV" -> Country("Tuvalu", "TV", "+688", R.drawable.flag_tuvalu)
            "TW" -> Country("Taiwan", "TW", "+886", R.drawable.flag_taiwan)
            "TZ" -> Country("Tanzania, United Republic Of", "TZ", "+255", R.drawable.flag_tanzania)
            "UA" -> Country("Ukraine", "UA", "+380", R.drawable.flag_ukraine)
            "UG" -> Country("Uganda", "UG", "+256", R.drawable.flag_uganda)
            "US" -> Country("United States", "US", "+1", R.drawable.flag_united_states_of_america)
            "UY" -> Country("Uruguay", "UY", "+598", R.drawable.flag_uruguay)
            "UZ" -> Country("Uzbekistan", "UZ", "+998", R.drawable.flag_uzbekistan)
            "VA" -> Country("Holy See (Vatican City State)", "VA", "+379", R.drawable.flag_vatican_city)
            "VC" -> Country("Saint Vincent & The Grenadines", "VC", "+1", R.drawable.flag_saint_vicent_and_the_grenadines)
            "VE" -> Country("Venezuela, Bolivarian Republic Of", "VE", "+58", R.drawable.flag_venezuela)
            "VG" -> Country("British Virgin Islands", "VG", "+1", R.drawable.flag_british_virgin_islands)
            "VI" -> Country("US Virgin Islands", "VI", "+1", R.drawable.flag_us_virgin_islands)
            "VN" -> Country("Vietnam", "VN", "+84", R.drawable.flag_vietnam)
            "VU" -> Country("Vanuatu", "VU", "+678", R.drawable.flag_vanuatu)
            "WF" -> Country("Wallis And Futuna", "WF", "+681", R.drawable.flag_wallis_and_futuna)
            "WS" -> Country("Samoa", "WS", "+685", R.drawable.flag_samoa)
            "XK" -> Country("Kosovo", "XK", "+383", R.drawable.flag_kosovo)
            "YE" -> Country("Yemen", "YE", "+967", R.drawable.flag_yemen)
            "YT" -> Country("Mayotte", "YT", "+262", R.drawable.flag_martinique)
            "ZA" -> Country("South Africa", "ZA", "+27", R.drawable.flag_south_africa)
            "ZM" -> Country("Zambia", "ZM", "+260", R.drawable.flag_zambia)
            "ZW" -> Country("Zimbabwe", "ZW", "+263", R.drawable.flag_zimbabwe)

            else -> Country("United States", "US", "+1", R.drawable.flag_united_states_of_america)
        }
    }
}
